### ISSUE TITLE
Multithreaded c++ code for opencv object detection 

### ISSUE THREAD

**Issue by ash97-ai** [jwdinius/yolov4-mask-detector#1]
Hi jwdinius. I’m referring your code for doing my assignment. I want to do object detection with opencv dnn yolov3 for object detection on windows. I’m new to c++ and Multithreading. Could you please help me? I didn’t find any resources online for this problem that’s why I’m checking with you.

**Comment by jwdinius** [comment]
Hello @ash97-ai.  I don't use Windows, but there are a number of concerns I have about trying to port this code.  The biggest of which is compiling OpenCV and Darknet with CUDA support.  The multithreading part of the code uses core C++, so I don't have concerns about portability in this regard.  Is there a language that you are more familiar with, like Python perhaps?  If so, I would suggest you try doing a line-by-line port of this app into your language of choice and then try to get that working.  The code is well-commented, so you should be able to go through the code and understand what each piece is doing.  Unfortunately, if you are really new to C++, I don't think this is the right application to get started with to learn.
